# Generated by Django 3.2.13 on 2022-05-23 20:38

from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image.models.code_uploaded_filename, verbose_name='uploaded image')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='Thumbnail of the uploaded image')),
                ('title', models.CharField(default='unknown', max_length=300)),
            ],
        ),
    ]
