# Generated by Django 3.2.13 on 2022-05-30 15:57

import django.core.validators
from django.db import migrations, models
import image.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField()),
                ('link', models.ImageField(blank=True, upload_to='temp')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=image.utils.code_uploaded_filename, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='uploaded image')),
                ('thumbnail_200px', models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail of uploaded image 200 px')),
                ('thumbnail_400px', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Thumbnail of uploaded image 400 px')),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
