# Generated by Django 3.2.13 on 2022-05-24 11:22

import django.core.validators
from django.db import migrations, models
import image.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to=image.models.code_uploaded_filename, validators=[django.core.validators.FileExtensionValidator(['.jpg', '.png'])], verbose_name='uploaded image'),
        ),
    ]
