# Generated by Django 3.2.13 on 2022-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Thumbnail of the uploaded image'),
        ),
    ]
