# Generated by Django 3.2.13 on 2022-05-24 12:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=32, unique=True, verbose_name='Url')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(300)])),
                ('expires', models.DateTimeField(verbose_name='Expires')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='image.uploadedimage')),
            ],
        ),
        migrations.DeleteModel(
            name='ExpireTime',
        ),
    ]
