# Generated by Django 3.2.13 on 2022-05-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20220524_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tempurl',
            old_name='expires',
            new_name='expired',
        ),
    ]
